export const API_URL = "http://localhost:8081/patient-data-processor"
export const USER_API_URL = "http://localhost:8081/patient-data-processor/api/v1.0/userrole"
export const DOCTOR_API_URL = "http://localhost:8081/patient-data-processor/api/v1.0/doctor"
export const PATIENT_API_URL = "http://localhost:8081/patient-data-processor/api/v1.0/patient"
export const REPORT_API_URL = "http://localhost:8081/patient-data-processor/api/v1.0/report"
export const RESULTS_API_URL = "http://localhost:8081/patient-data-processor/api/v1.0/results"
export const PRESCRIPTION_API_URL = "http://localhost:8081/patient-data-processor/api/v1.0/prescription"
